title: Employees Data Analysis
description: >
  In this project I used SQL queries to retrieve data from the employees database.
  After extracting relevant data, I created an interactive dashboard using Tableau
  to illustrate the outcomes in a clear and accessible manner. 
show_downloads: true
theme: jekyll-theme-slate
