title: Employees Data Analysis
description: >
  In this project, I utilized SQL and Tableau to analyse employees data.
  I extracted data with SQL and created interactive visualizations using Tableau.
show_downloads: true
theme: jekyll-theme-slate
